# Generated by Django 3.2 on 2021-06-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('event_link', models.URLField()),
            ],
        ),
    ]
