# Generated by Django 3.2 on 2021-08-05 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourReservations',
            fields=[
                ('reservationId', models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=12)),
                ('tourDate', models.CharField(blank=True, default='', max_length=50)),
                ('meetTime', models.CharField(blank=True, default='', max_length=50)),
                ('tourType', models.CharField(choices=[('bouldering', 'Bouldering'), ('hiking', 'Hiking'), ('rock art', 'Rock Art'), ('technical climbing', 'Technical Climbing')], max_length=20)),
                ('booked_by_user', models.BigIntegerField(blank=True, default=0)),
                ('guide_assigned', models.BigIntegerField(blank=True, default=0)),
                ('destination', models.CharField(max_length=100)),
                ('tourStyle', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=8)),
                ('comments', models.TextField(blank=True, default='', max_length=300)),
                ('numberOfPersons', models.IntegerField(default=1)),
                ('isAccept', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourType', models.CharField(choices=[('bouldering', 'Bouldering'), ('hiking', 'Hiking'), ('rock art', 'Rock Art'), ('technical climbing', 'Technical Climbing')], max_length=20)),
                ('tourStyle', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=8)),
                ('tourDescription', models.TextField(blank=True, max_length=500)),
                ('tourId', models.IntegerField(default=False)),
                ('maxPersonAllowed', models.IntegerField(default=1)),
                ('variableCost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fixedCost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuideTourMapping',
            fields=[
                ('guideTourId', models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('meetTime', models.CharField(blank=True, default='', max_length=50)),
                ('tourDate', models.CharField(blank=True, default='', max_length=50)),
                ('tourType', models.CharField(choices=[('bouldering', 'Bouldering'), ('hiking', 'Hiking'), ('rock art', 'Rock Art'), ('technical climbing', 'Technical Climbing')], max_length=20)),
                ('tourStyle', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=8)),
                ('destination', models.CharField(blank=True, default='', max_length=100)),
                ('clients', models.TextField(default='', null=True)),
                ('guide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='GuideInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceType', models.CharField(choices=[('fix', 'Fix'), ('negotiable', 'Negotiable')], max_length=11)),
                ('fix_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('variable_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('destination', models.CharField(blank=True, default='', max_length=100)),
                ('guide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
