# Generated by Django 3.2 on 2021-08-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huecotours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidetourmapping',
            name='clients',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
