# Generated by Django 3.2.6 on 2021-08-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huecotours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidetourmapping',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
