# Generated by Django 3.2 on 2021-08-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huecotours', '0002_alter_guidetourmapping_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidetourmapping',
            name='guide',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
