# Generated by Django 3.2 on 2021-08-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huecotours', '0003_alter_guidetourmapping_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourreservations',
            name='numberOfPersons',
        ),
        migrations.AddField(
            model_name='guideinfo',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='guideinfo',
            name='tourType',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='guidetourmapping',
            name='numberOfPersons',
            field=models.IntegerField(default=0),
        ),
    ]
