# Generated by Django 3.2 on 2021-08-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huecotours', '0004_auto_20210810_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='maxPersonAllowed',
            field=models.IntegerField(default=0),
        ),
    ]
