# Generated by Django 3.2 on 2021-08-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huecotours', '0005_alter_tours_maxpersonallowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourreservations',
            name='number_of_clients',
            field=models.IntegerField(default=1),
        ),
    ]
