# Generated by Django 3.2.6 on 2021-08-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huecotours', '0006_tourreservations_number_of_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourreservations',
            name='tansaction_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourreservations',
            name='transaction_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tourreservations',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
